DROP TABLE EXEMPLARES_ACERVO;
CREATE TEMPORARY TABLE EXEMPLARES_ACERVO(
	REGISTRO_SISTEMA integer,
	TITULO TEXT,
	SUB_TITULO TEXT,
	ASSUNTO TEXT,
	AUTOR TEXT NOT NULL,
	TIPO_MATERIAL CHARACTER VARYING(25) NOT NULL,
	QUANTIDADE integer,
	ANO TEXT,
	EDICAO TEXT,
	EDITORA CHARACTER VARYING(300) NOT NULL,
	ISBN TEXT,
	ISSN TEXT);

COPY EXEMPLARES_ACERVO
FROM '/home/exemplares-acervo.csv'
DELIMITER ';' CSV HEADER;


INSERT INTO MATERIAIS (TIPO_MATERIAL)
SELECT DISTINCT TIPO_MATERIAL
FROM EXEMPLARES_ACERVO
WHERE COALESCE(TIPO_MATERIAL, '') <> '';
	
INSERT INTO AUTORES (AUTOR)
SELECT DISTINCT AUTOR
FROM EXEMPLARES_ACERVO
WHERE COALESCE(AUTOR,'') <> '';
	
INSERT INTO EDITORAS (EDITORA)
SELECT DISTINCT EDITORA
FROM EXEMPLARES_ACERVO
WHERE COALESCE(EDITORA, '') <> '';

INSERT INTO LIVROS (
		REGISTRO_SISTEMA,
		TITULO,
		SUB_TITULO,
		ASSUNTO,
		EDICAO,
		ANO,
		ISSN,
		ISBN,
		ID_AUTOR,
		ID_MATERIAL,
		ID_EDITORA)
SELECT  EA.REGISTRO_SISTEMA,
		EA.TITULO,
		EA.SUB_TITULO,
		EA.ASSUNTO,
		EA.EDICAO,
		EA.ANO,
		EA.ISSN,
		EA.ISBN,
		A.ID,
		M.ID,
		E.ID
FROM EXEMPLARES_ACERVO EA
JOIN AUTORES A
  ON A.AUTOR = EA.AUTOR
JOIN EDITORAS E
  ON E.EDITORA = EA.EDITORA
JOIN MATERIAIS M
  ON M.TIPO_MATERIAL = EA.TIPO_MATERIAL;

